"""Render every outputs/plots/full_matrix/*.svg to a same-name .png.

These PNGs are a convenience export for pasting into slide decks -- the
SVGs (regenerated by ``build_full_matrix_summary.py``) remain the source
of truth. Rerun this after any change to the SVGs to keep the PNGs in
sync. Requires a headless Chromium/Chrome binary (google-chrome,
chromium, or chromium-browser) on PATH; there is no pure-Python SVG
rasterizer in this project's dependencies.
"""

from __future__ import annotations

import re
import shutil
import subprocess
from pathlib import Path

PLOT_DIR = Path("outputs/plots/full_matrix")
SCALE_FACTOR = 2  # render at 2x pixel density for crisp slide placement


def find_chrome_binary() -> str:
    for name in ("google-chrome", "chromium-browser", "chromium"):
        path = shutil.which(name)
        if path:
            return path
    raise RuntimeError(
        "no headless Chromium/Chrome binary found on PATH "
        "(tried google-chrome, chromium-browser, chromium)"
    )


def svg_dimensions(svg_path: Path) -> tuple[int, int]:
    text = svg_path.read_text(encoding="utf-8")
    width_match = re.search(r'<svg[^>]*\swidth="(\d+)"', text)
    height_match = re.search(r'<svg[^>]*\sheight="(\d+)"', text)
    if not width_match or not height_match:
        raise ValueError(f"could not find width/height on <svg> in {svg_path}")
    return int(width_match.group(1)), int(height_match.group(1))


def render(chrome: str, svg_path: Path) -> Path:
    width, height = svg_dimensions(svg_path)
    png_path = svg_path.with_suffix(".png")
    subprocess.run(
        [
            chrome,
            "--headless",
            "--disable-gpu",
            "--no-sandbox",
            f"--force-device-scale-factor={SCALE_FACTOR}",
            f"--window-size={width},{height}",
            f"--screenshot={png_path}",
            svg_path.resolve().as_uri(),
        ],
        check=True,
        capture_output=True,
    )
    return png_path


def main() -> int:
    chrome = find_chrome_binary()
    svg_paths = sorted(PLOT_DIR.glob("*.svg"))
    if not svg_paths:
        raise SystemExit(f"no SVGs found under {PLOT_DIR}")
    for svg_path in svg_paths:
        png_path = render(chrome, svg_path)
        print(f"{svg_path} -> {png_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
